[package]
name = "fluster_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib", "lib"]
name = "fluster_rust"

[dependencies]
async-trait = "0.1.81"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
uniffi = "0.29"
