[package]
name = "fluster_bibliography"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib", "lib"]
name = "fluster_bibliography"

[dependencies]
hayagriva = { version = "0.9.1", features = ["strum"] }
uniffi = "0.29"
fluster_core_utilities = { path = "../fluster_core_utilities/" }
citeproc = { path = "../citeproc-rs/crates/citeproc/" }
log = "0.4.29"
rayon.workspace = true
rust-embed = "8.11.0"
strum_macros = "0.27.2"
strum = "0.27.2"
serde.workspace = true

