[package]
name = "fluster_bibliography"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib", "lib"]
name = "fluster_bibliography"

[dependencies]
hayagriva = "0.9.1"
uniffi = "0.29"

