[package]
name = "fluster_swift_mdx_parser"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib", "lib"]
name = "fluster_swift_mdx_parser"

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uniffi = { workspace = true }
fluster_core_utilities = { path = "../fluster_core_utilities/" }
fluster_pre_parser = { path = "../fluster_pre_parser/" }
serde_bibtex = { version = "0.7.1", features = ["all"] }
tokio = { workspace = true, features = ["full"] }

[profile.release]
lto = "fat"
