[package]
name = "uniffi_bindgen"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
# This can be whatever name makes sense for your project, but the rest of this tutorial assumes uniffi-bindgen.
name = "uniffi-bindgen"
path = "uniffi_bindgen.rs"

[dependencies]
uniffi = { workspace = true, features = ["cli"] }

[lints]
workspace = true
