[package]
name = "fluster_database"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lancedb = { version = "0.19", features = ["polars"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
fluster_core_utilities = { path = "../fluster_core_utilities/" }
arrow-schema = "54.1"
arrow-array = "54.1"
serde_arrow = { version = "0.13.3", features = ["arrow-54"] }
chrono = { version = "0.4", features = ["now", "serde"] }
dirs = "6.0.0"
futures = "0.3.31"
specta.workspace = true
tokio = { workspace = true, features = ["full"] }
log = "0.4.29"
strum_macros = "0.27.2"
strum = "0.27.2"
ignore = "0.4.25"

[lints]
workspace = true
