[package]
name = "fluster_lsp"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
tower-lsp = "0.20.0"

[lints]
workspace = true
