[package]
name = "fluster_pre_parser"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
uniffi = { workspace = true }
fluster_core_utilities = { workspace = true }
serde = { workspace = true }
async-trait = { workspace = true }
regex = { workspace = true }
rayon = { workspace = true }
tokio = { workspace = true, features = ["full"] }
gray_matter = "0.3.2"
strum_macros = "0.27.2"
flatbuffers.workspace = true
chrono = { workspace = true }


[profile.release]
lto = "fat"
