[package]
name = "fluster_core_utilities"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
uniffi = { workspace = true }
flatbuffers = { workspace = true }
serde.workspace = true
strum_macros = "0.27.2"
typeshare.workspace = true
specta = { workspace = true }
chrono = { workspace = true }
arrow-schema = { workspace = true }
arrow-array = { workspace = true }
serde_arrow = { workspace = true }
tauri = { workspace = true }
tauri-specta = {workspace = true}
glob = "0.3.3"
ignore = "0.4.25"
crossbeam = { version = "0.8.4", features = [
    "alloc",
    "std",
    "crossbeam-channel",
] }
crossbeam-channel = "0.5.15"
tokio = { workspace = true, features = ["full"] }
lancedb = { workspace = true }
dirs = "6.0.0"
log = "0.4.29"
strum = { version = "0.27.2", features = ["derive"] }
uuid = { version = "1.19.0", features = ["v4"] }
futures = "0.3.31"
filetime = "0.2.26"
gray_matter = "0.3.2"
ndarray = { version = "0.17.2", features = ["rayon"] }
rayon.workspace = true
regex.workspace = true

[profile.release]
lto = "fat"
