[package]
name = "fluster_core_utilities"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
thiserror = { workspace = true }
uniffi = { workspace = true }
flatbuffers = { workspace = true }
serde.workspace = true
strum_macros = "0.27.2"
typeshare.workspace = true
